### ISSUE TITLE
Hard to replicate with new models 

### ISSUE THREAD

**Issue by femiliani** [novoalab/modPhred#2]
First off, great work! it's always really nice when things work straight out of the box and really shows how much care you put into it if a beginner like me can get it to work. It also tackles a really important need in the nanopore methylation calling repertoire. 

The model you use the dam-dcm specific one was removed from guppy 4.5.2 and the currently available models struggle to replicate your test data results. Since the ONT software download page forces your to download the latest guppy newer users won't be able to use the same basecaller. This is not really an issue of your package but I wasn't sure where to post it because this solution was a little harder to come by than it should have been. For people looking for older versions for linux just change the version number to whichever version you want to install, 4.4.2 is the latest distribution with the dam-dcm still available:
wget https://mirror.oxfordnanoportal.com/software/analysis/ont-guppy_4.4.2_linux64.tar.gz
With the dam-dcm model I was once again able to replicate your test data. 

Currently available models in guppy 4.5.2 and rerio:
Guppy: dna_r9.4.1_450bps_modbases_5mc_hac.cfg causes most of the 5mC to be CpGs even in bacteria... either we stumbled onto some amazing bacterial biology or it's just not working. (NB this 5mC model is the same as the 5mC one in rerio) 
Rerio: res_dna_r941_min_modbases-all-context_v001.cfg gets a lot closer but below you can see that the methylations are more spread and less accurate. 

EDIT: Bottom panel is with the rerio model, top panel is with your pre-basecalled dataset (sorry got that switched up pre-edit)
![image](https://user-images.githubusercontent.com/58233098/113306518-2c5cd180-92d2-11eb-82ab-67a9adbe9ec1.png)

Got to be honest, it's a little worrisome how much difference the basecalling model can make. Definitely something I need to spend more time looking into. But at least this is a quick fix for other people who have the latest version of guppy and were struggling like me. 

And thanks again for putting this package together.

**Comment by lpryszcz** [comment]
Hi @femiliani , first of all thanks for all the nice words! 

I didn't know about removal of dam/dcm models from guppy v4.5+. To be frank we haven't used anything newer than 4.4.1, since updating GPU drivers & CUDA is rather complicated in the institute-wide computing cluster... 

Regarding rerio modification-aware models, I've noticed some time ago how bad it's on bacteria... It's definitely no new biology ;)
The quality of the model depends on multiple factors and it's really a pity @nanoporetech isn't transparent about their model training protocols. I'm really surprised they moved their experimental m5C model into production. 

Still, you should be able to use older models with newer guppy versions (those are typically backward-compatible). So I've added dcm/dam model into the repository in the [data dir](/novoalab/modPhred/tree/main/data) if you want to play with it. I'm not sure if it'll work with v4.5.2 since there is new model compression being introduced, but you can give it a go (unfortunately I can't test it myself). 

Alternatively, you can get older versions of guppy, just replacing the version in the URL, for example (those are CUDA-compatible): 
- v4.0.15 https://mirror.oxfordnanoportal.com/software/analysis/ont-guppy_4.0.15_linux64.tar.gz
- v3.6.1 https://mirror.oxfordnanoportal.com/software/analysis/ont-guppy_3.6.1_linux64.tar.gz

Hope it helps! And I'll be happy to hear more feedback :)
