### ISSUE TITLE
Silently failing to map reads 

### ISSUE THREAD

**Issue by 690645258** [novoalab/modPhred#4]
Hi,

When I run modphred on two pre basecalled samples it will get up to aligning and then fail silently, try to continue to samtools sorting but no bam exists.
<img width="708" alt="Screenshot 2022-02-11 at 10 05 56" src="https://user-images.githubusercontent.com/36636000/153572792-b723f89f-71ba-4fc0-ac49-3ea119957793.png">

When I look in the minimap2 workspace.log I can see only two lines:

[M::mm_idx_gen::49.955*1.50] collected minimizers
[M::mm_idx_gen::56.698*3.16] sorted minimizers

Running guppy_align.py by itself I see similar behaviour, minimap2 runs in processes even after the guppy_align.py script has terminated, with no other output other than the log like above.

Is there an easy way of manually aligning and sorting with samtools to move on with the later steps of the pipeline? 
I've run the samples individually with no issue but would like to compare and contrast them. Is there a way I can concatenate the individual runs together to do some visualisations?

Thanks for any help!

**Comment by lpryszcz** [comment]
Hi @690645258 , there is samtools error related to `libcrypto`. Sort it out and try running modPhred first on the test set. 

btw, both of your samples are named `workspace`. you can give to modPhred 1 directory higher ie. using `-ri sample1/ sample2/` instead of `-ri sample1/workspace sample2/workspace`.  
If you use `-r`, modPhred will look recursively inside the `sample1` and `sample2` directories. 

Cheers,

**Comment by 690645258** [comment]
Can't believe I didn't spot that... thanks! Tested with the test dataset and ran through everything no issue in 30 mins.

Anyone else having this issue it seems to be conda related as it uses a version of openssl which uses lybcrypto.so.1.1.0. 

To fix this, in the conda installation stage add openssl=1.0.2p=h14c3975_1002 to the list of packages to install
